Numpy numercial python


In [2]:
import  numpy as np


In [1]:
from time import process_time

In [ ]:
list = [i for i in range(10000)]
start_time = process_time()
list = [i+5 for i in range(10000)]
end_time = process_time()
time = end_time - start_time
print(time)

0.0017455640000001438


In [ ]:
nparray = np.array([i for i in range(1000000)])
start_time = process_time()
nparray +=5
end_time = process_time()
time = end_time - start_time
print(time)

0.0017694040000009181


Numpy Arrays


In [ ]:
list = [1,2,3,4,5]
print(list)
type(list)

[1, 2, 3, 4, 5]


list

In [ ]:
nparray = np.array([1,2,3,45,5])
print(nparray)
type(nparray)

[ 1  2  3 45  5]


numpy.ndarray

In [ ]:
#creating 1D array
n = np.array([1,2,3,4,5])
print(n)
type(n)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
n.shape

(1, 5)

In [ ]:
#creating 2D array
b = np.array([(2,3,4,22), (3,2,2,623)])
print(b)

[[  2   3   4  22]
 [  3   2   2 623]]


In [ ]:
b.reshape

<function ndarray.reshape>

In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3),(4,2,42)],dtype =float)
print(c)

[[ 1.  2.  3.]
 [ 4.  2. 42.]]


initail place holder

In [ ]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z = np.full((4,5),9)
print(z)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [ ]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy arr with random value
b = np.random.random((3,5))
print(b)

[[0.06434294 0.17593607 0.36410998 0.18755445 0.06576482]
 [0.9891842  0.10562339 0.83665707 0.34164768 0.3785164 ]
 [0.78513876 0.95453129 0.03696778 0.85448934 0.43971125]]


In [ ]:
#random value in terms of integer within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[60 46 41 64 96]
 [29 88 70 22 15]
 [92 70 80 24 24]]


In [ ]:
#array of evenly spaced valued
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced valued
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
#convert a list to numpy array
list2 = [10,203,202,42]
np_array = np.array(list2)
print(np_array)
type(np_array)


[ 10 203 202  42]


numpy.ndarray

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[31 57 77 19 15]
 [68 44 77 59 88]
 [84 23 75 25 41]
 [51 24 13 76 48]
 [86 79 86 12 12]]


analyzing a numpy array

In [ ]:
print(c.shape)

(5, 5)


In [ ]:
#number of dimension
print(c.ndim)

2


In [ ]:
# number of element in an array
print(c.size)

25


In [ ]:
# checking the data type
print(c.dtype)

int64


Mathematical operations on a np array


In [ ]:
list1 = [2,3,21,3]
list2 = [4,33,2,3]
print(list1+list2)

[2, 3, 21, 3, 4, 33, 2, 3]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)
print(a+b)
print(a-b)
print(a/b)
print(a*b)

[[5 2 7]
 [1 3 3]
 [9 9 8]]
[[15 12 10]
 [11 11 18]
 [15 17 11]]
[[20 14 17]
 [12 14 21]
 [24 26 19]]
[[-10 -10  -3]
 [-10  -8 -15]
 [ -6  -8  -3]]
[[0.33333333 0.16666667 0.7       ]
 [0.09090909 0.27272727 0.16666667]
 [0.6        0.52941176 0.72727273]]
[[ 75  24  70]
 [ 11  33  54]
 [135 153  88]]


In [3]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[20 18 22]
 [17 21 22]
 [23 14 23]]
[[-14  -6 -14]
 [-15  -9 -14]
 [-13 -10 -15]]
[[51 72 72]
 [16 90 72]
 [90 24 76]]
[[0.17647059 0.5        0.22222222]
 [0.0625     0.4        0.22222222]
 [0.27777778 0.16666667 0.21052632]]


array manupilation

In [6]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 8 4]
 [5 4 9]]
(2, 3)


In [7]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)


[[9 5]
 [8 4]
 [4 9]]
(3, 2)


In [8]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 2 7]
 [1 8 2]]
(2, 3)


In [11]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[2 2]
 [7 1]
 [8 2]]
(3, 2)
