In [ ]:
# want to create 2d array
import numpy as np
np.zeros((3,4))
x5 = np.ones(5)
#update a value
print(x5)
x5[2]= 4
print(x5)
#create 3D array
new_array = np.zeros((3,4,5))
print(new_array)
new_array[0]


In [12]:
#shape method
a = np.zeros(5)
print(a)
a[2:5]

[0. 0. 0. 0. 0.]


array([0., 0., 0.])

In [26]:
twoD_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD_array)
print(twoD_array[2])
print(twoD_array[2:,1])
# error print(twoD_array[2:1])
print(twoD_array[2:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
[8]
[9]
