In [ ]:
#library
import math as m
x = m.gcd(123,21);
print(x)
print('a')


In [5]:
import math
y = math.gcd(125,35);
print(y);

5


In [12]:
import numpy as np
demo =[1,2,'abc']
#print(demo)
np.array(demo)
print(demo)

[1, 2, 'abc']


In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [20]:
y = np.zeros(3,int)
print(y)
y.dtype
x = np.ones(4,int)
print(x)
x.dtype

[0 0 0]
[1 1 1 1]


dtype('int64')

# New Section